model:
  arch: "LRN"
  max_channels: 256
  activation: ("LeakyReLU", [0.2, True] )
  upsample: "bilinear"
  use_crp: True
  criterion: (("LogDepthL1Loss",  1.0), )
  predict_log_depth: True
  concat_mask: True

  backbone:
    arch: "tf-efficientnet-lite-b0"
    imagenet: True

train:
  batch_size: 32
  lr: 0.0001
